export const SUPPORTED_CHAINS_TESTNET = {
  ZKEVM: 280,
  // ARBITRUM_RINKEBY: 421611,
  // FUJI: 43113,
};

export const SUPPORTED_CHAINS_MAINNET = {
  AVALANCHE: 43114,
  ARBITRUM: 42161,
};

export const SUPPORTED_CHAIN_NAMES = {
  [SUPPORTED_CHAINS_TESTNET.ZKEVM]: 'zkEVM',
  // [SUPPORTED_CHAINS_TESTNET.ARBITRUM_RINKEBY]: 'Arbitrum Rinkeby',
  // [SUPPORTED_CHAINS_TESTNET.FUJI]: 'Avalanche Fuji',
};

export const SUPPORTED_CHAIN_IDS = Object.values(SUPPORTED_CHAINS_TESTNET);
